"""add1

Revision ID: 8c74125b223f
Revises: 6f48f64ff4ca
Create Date: 2025-04-19 15:31:32.782067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c74125b223f'
down_revision = '6f48f64ff4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_score')
        batch_op.drop_column('highest_score')

    # ### end Alembic commands ###
